### ISSUE TITLE
Rendered tweets are centered within their div

### ISSUE THREAD

**Issue by stevehind** [stevehind/delete-my-tweets#3]
Tweets that render aren't centered within their div. Have tried making a CSS class to do this, and have failed. Would love some help.

<img width="1424" alt="Screen Shot 2020-12-22 at 1 18 47 PM" src="https://user-images.githubusercontent.com/17911380/102934032-3b70ef80-4458-11eb-8dd5-e4fd097c63e6.png">

**Comment by nerdcha** [comment]
Let me offer two solutions and explain how I figured them out.

First, let's figure out exactly what's happening. Fire up the old Inspect Element and click around until you see something that looks uncentered, which turns out to be the `.twitter-tweet` divs. Notice that the Computed tab on the right has blank values in the margins? That means `¯\_(ツ)_/¯`, the browser cannot compute them.

<img width="1479" alt="Screen Shot 2020-12-23 at 10 05 00 am" src="https://user-images.githubusercontent.com/7462210/102941514-02dc1f00-4507-11eb-9a4a-ac893d2839bd.png">

Auto-centering with margins is a frequent CSS headscratcher, and I always forget how it works, but a quick google of `css margin center auto` leads to the [answer](https://stackoverflow.com/a/963646/5881346): you need to muck around with ~the _parent_, not the thing being centered~ (edit: typed it the wrong way around 🤦). You can confirm that by directly editing the `element.style` in developer tools, and/or by tinkering with your `style.css` in the Sources tab. So the most direct way to fix your problem is by adding this to your stylesheet:
```
.center div {
    margin: 0 auto;
}
```

However, this would be a natural place to use [Flexbox](https://jonitrythall.com/flexbox-cheatsheet), particularly if you don't care about supporting 10 year-old versions of IE. That would involve adding
```
    display: flex;
    flex-direction: column;
    align-items: center;
```
to the `.center` class. That may some flow-on effects elsewhere in the page—it's hard to do Flexbox in just one part of the page, you tend to have to reshape your whole structure—so would require a bit more thought.

In general, don't be intimidated by CSS! It's interesting, powerful, and fun. I'd suggest you spend some time browsing around [Lea Verou's blog](https://lea.verou.me/) or [CSS Tricks](https://css-tricks.com/) to help with feeling more at home. Verou's [book](https://books.google.com.au/books?id=_oVHCgAAQBAJ&newbks=1&newbks_redir=0&lpg=PP1&pg=PP1#v=onepage&q&f=false) is great and definitely worth a read, though it's a bit out of date now (it predates Flexbox, for instance).

**Comment by stevehind** [comment]
🙏 thank you so much @nerdcha ! I think the big thing I was missing was this:

> Notice that the Computed tab on the right has blank values in the margins? That means ¯\_(ツ)_/¯, the browser cannot compute them.

I wasn't sure how to debug CSS in inspect -- e.g. that when computed shows blank it means the browser can't compute what's there. Super helpful.

 Will look at the reading material you mentioned.

**Comment by stevehind** [comment]
#4
